export const books = [
    { id:1,
    img:'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71sBtM3Yi5L._AC_UY327_FMwebp_QL65_.jpg',
    title:'The Power of your subconscious Mind',
    author:'By Ronak Singh',
  },
  { id:2,
    img:'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71+6w5Xpj8L._AC_UY327_FMwebp_QL65_.jpg',
    title:'Dont Believe',
    author:'Ankur Dahiya',
  },
  { id:3,
    img:'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91Uek-IKqzL._AC_UY327_FMwebp_QL65_.jpg',
    title:'MY new book',
    author:'Antil',
  },
  { id:4,
    img:'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61qHANm1UJL._AC_UY327_FMwebp_QL65_.jpg',
    title:'Nayi kitaab',
    author:'Ankur',
  },
  { id:5,
    img:'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61Iecjs2maL._AC_UY327_FMwebp_QL65_.jpg',
    title:'Hello Guys',
    author:'Ankur Dahiya',
  }]